/* Closed cross-world messages. Media URLs and binary never reach panel or API controls. */
(function(root){
  'use strict';
  const S=root.KurukinSecurity,prefix='KURUKIN_',audioCodes=['VIDEO_NOT_AVAILABLE_IN_CURRENT_SCAN','AUDIO_MEDIA_NOT_FOUND','AUDIO_MEDIA_FETCH_FAILED','AUDIO_MEDIA_HTTP_ERROR','AUDIO_MEDIA_TIMEOUT','AUDIO_MEDIA_CONTENT_TYPE','AUDIO_DECODE_FAILED','AUDIO_RESAMPLE_FAILED','AUDIO_SPEECH_DETECTOR_FAILED','AUDIO_CLASSIFIER_FAILED','AUDIO_WAV_FAILED','AUDIO_CONTEXT_INVALIDATED'];
  const exact=(v,keys)=>!!v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));
  const id=v=>typeof v==='string'&&/^[a-zA-Z0-9_-]{8,80}$/.test(v),videoId=v=>typeof v==='string'&&/^\d{5,30}$/.test(v),integer=S.integer;
  const user=v=>typeof v==='string'&&/^[\w.]{1,64}$/.test(v);
  const videoKeys=['id','author','nickname','caption','created_at','views','likes','comments','shares','favorites','duration','url','music_id','music_title','music_author','music_original'];
  function video(v){return exact(v,videoKeys)&&videoId(v.id)&&user(v.author)&&typeof v.nickname==='string'&&v.nickname.length<=256&&typeof v.caption==='string'&&v.caption.length<=10000&&['created_at','views','likes','comments','shares','favorites'].every(k=>typeof v[k]==='number'&&Number.isFinite(v[k])&&v[k]>=0)&&(v.duration===null||typeof v.duration==='number'&&Number.isFinite(v.duration)&&v.duration>=0)&&[v.music_id,v.music_title,v.music_author].every(x=>x===null||typeof x==='string')&&(v.music_original===null||typeof v.music_original==='boolean')&&v.url===`https://www.tiktok.com/@${v.author}/video/${v.id}`;}
  function diagnostic(v){return exact(v,['page','httpStatus','tiktokStatusCode','itemCount','cursorPresent','hasMore'])&&integer(v.page)&&(v.httpStatus===null||integer(v.httpStatus))&&(v.tiktokStatusCode===null||integer(v.tiktokStatusCode))&&integer(v.itemCount)&&typeof v.cursorPresent==='boolean'&&typeof v.hasMore==='boolean';}
  const base=p=>exact(p,['videoId'])&&videoId(p.videoId);
  const timing=p=>['fetchMp4Ms','decodeResampleMs','wavEncodeMs','totalAcquisitionMs'].every(k=>p[k]===null||integer(p[k]));
  const audioMeta=p=>integer(p.candidate)&&p.candidate<=3&&['none','bitrateInfo','playAddr','PlayAddrStruct','downloadAddr'].includes(p.source)&&(p.httpStatus===null||integer(p.httpStatus))&&['unknown','other','video/mp4','video/webm','video/quicktime','application/octet-stream','binary/octet-stream','application/mp4'].includes(p.contentType)&&(p.contentLength===null||integer(p.contentLength))&&integer(p.bytes)&&integer(p.sampleRate)&&integer(p.channels)&&integer(p.wavBytes)&&(p.expectedDuration===null||typeof p.expectedDuration==='number')&&typeof p.duration==='number'&&timing(p);
  const metrics=['candidate','source','httpStatus','contentType','contentLength','bytes','expectedDuration','sampleRate','channels','duration','wavBytes','fetchMp4Ms','decodeResampleMs','wavEncodeMs','totalAcquisitionMs'];
  const acquisitionStages=['FETCH_MP4','DECODE_AUDIO','RESAMPLE_PCM','ENCODE_WAV','HANDOFF_WAV','HTTP_UPLOAD'];
  const acquisitionCodes=['VIDEO_NOT_AVAILABLE','MEDIA_NOT_FOUND','FETCH_FAILED','FETCH_TIMEOUT','UNSUPPORTED_CONTENT_TYPE','DECODE_FAILED','RESAMPLE_FAILED','WAV_ENCODE_FAILED','WAV_TOO_LARGE','WAV_INVALID','WAV_BASE64_INVALID','BASE64_ENCODE_FAILED','RUNTIME_MESSAGE_FAILED','NETWORK_ERROR','INVALID_RESPONSE','UPLOAD_FAILED','ACQUISITION_CANCELLED'];
  const safeAcquisitionCode=value=>acquisitionCodes.includes(value)||/^HTTP_[1-5]\d\d$/.test(value);
  const optionalTiming=value=>value===null||integer(value);
  function acquisitionState(p){return exact(p,['requested','uploaded','failed','currentVideoId','lastStatus','lastUploadMs','phase','lastErrorStage','lastErrorCode','fetchMp4Ms','decodeMs','wavMs','handoffMs','uploadMs'])&&integer(p.requested)&&p.requested<=10&&integer(p.uploaded)&&p.uploaded<=p.requested&&integer(p.failed)&&p.failed<=p.requested&&(p.currentVideoId===null||videoId(p.currentVideoId))&&(p.lastStatus===null||p.lastStatus===202||p.lastStatus===0)&&(p.lastUploadMs===null||integer(p.lastUploadMs))&&(p.lastErrorStage===null||acquisitionStages.includes(p.lastErrorStage))&&(p.lastErrorCode===null||safeAcquisitionCode(p.lastErrorCode))&&((p.lastErrorStage===null)===(p.lastErrorCode===null))&&['fetchMp4Ms','decodeMs','wavMs','handoffMs','uploadMs'].every(key=>optionalTiming(p[key]))&&['idle','reserved','acquiring','secured','failed','complete'].includes(p.phase);}
  const backendDiagnostic=p=>exact(p,['baseHost','httpStatus','errorCode'])&&p.baseHost==='intelligence.kuruk.in'&&(p.httpStatus===null||integer(p.httpStatus))&&['NETWORK_ERROR','HTTP_RESPONSE','INVALID_RESPONSE','RUNTIME_ERROR'].includes(p.errorCode);
  function valid(m,channel){try{if(!exact(m,['version','channel','type','scanId','payload'])||m.version!==5||m.channel!==channel||!id(m.scanId))return false;const p=m.payload;
    if(m.type.startsWith('KURUKIN_AUDIO_')){if(!p||!videoId(p.videoId))return false;if(['KURUKIN_AUDIO_CHECK','KURUKIN_AUDIO_AVAILABLE','KURUKIN_AUDIO_DOWNLOAD','KURUKIN_AUDIO_RELEASE','KURUKIN_AUDIO_CANCEL'].includes(m.type))return false; if(m.type==='KURUKIN_AUDIO_REQUEST')return channel==='content'&&exact(p,['videoId','experimental','extensionBase'])&&typeof p.experimental==='boolean'&&typeof p.extensionBase==='string'&&/^chrome-extension:\/\/[a-p]{32}\/$/.test(p.extensionBase);if(m.type==='KURUKIN_AUDIO_START')return exact(p,['videoId']);if(m.type==='KURUKIN_AUDIO_READY')return exact(p,['videoId',...metrics,'buffer'])&&audioMeta(p)&&Object.prototype.toString.call(p.buffer)==='[object ArrayBuffer]'&&p.buffer.byteLength===p.wavBytes;if(m.type==='KURUKIN_AUDIO_ERROR')return exact(p,['videoId',...metrics,'terminal','code','phase','name','message','stack'])&&audioMeta(p)&&typeof p.terminal==='boolean'&&audioCodes.includes(p.code)&&['fetch','decode','resample','wav'].includes(p.phase)&&p.name==='AudioError'&&p.message===p.code&&p.stack===`KurukinAudio.extract:${p.phase}`;return ['KURUKIN_AUDIO_MEDIA_FETCHING','KURUKIN_AUDIO_MEDIA_FETCHED','KURUKIN_AUDIO_DECODING','KURUKIN_AUDIO_RESAMPLING'].includes(m.type)&&exact(p,['videoId',...metrics])&&audioMeta(p);}
    if(['KURUKIN_ACQUISITION_PREPARE','KURUKIN_ACQUISITION_START'].includes(m.type))return channel==='panel'&&exact(p,[]);
    if(m.type==='KURUKIN_ACQUISITION_TARGET'||m.type==='KURUKIN_EXPERIMENTAL_AUDIO_REQUEST')return channel==='panel'&&base(p);
    if(m.type==='KURUKIN_ACQUISITION_STATE')return channel==='content'&&acquisitionState(p);
    if(m.type==='KURUKIN_EXPERIMENTAL_AUDIO_RESULT')return channel==='content'&&exact(p,['videoId','sileroMs','yamnetMs','audioClassification'])&&videoId(p.videoId)&&integer(p.sileroMs)&&integer(p.yamnetMs)&&(p.audioClassification===null||['speech','music','singing','mixed','ambiguous'].includes(p.audioClassification));
    if(m.type==='KURUKIN_ACQUISITION_ERROR')return channel==='content'&&exact(p,['code','diagnostic'])&&['BACKEND_UNAVAILABLE','BACKEND_REJECTED','RESERVATION_REQUIRED','AUDIO_UPLOAD_FAILED'].includes(p.code)&&backendDiagnostic(p.diagnostic);
    switch(m.type){case prefix+'PANEL_READY':case prefix+'PANEL_CLOSE':case prefix+'CONTEXT_GET':case prefix+'SCAN_CANCEL':return exact(p,[]);case prefix+'SCAN_START':return exact(p,['target'])&&[50,100,200].includes(p.target);case prefix+'CONTEXT':return exact(p,['username','loggedIn'])&&(p.username===null||user(p.username))&&typeof p.loggedIn==='boolean';case prefix+'SCAN_PROGRESS':return exact(p,['phase','total','page','elapsedMs','debug'])&&['preparing','requesting','waiting','received'].includes(p.phase)&&integer(p.total)&&p.total<=200&&integer(p.page)&&integer(p.elapsedMs)&&diagnostic(p.debug);case prefix+'SCAN_COMPLETE':return exact(p,['videos','cancelled','elapsedMs'])&&Array.isArray(p.videos)&&p.videos.length<=200&&p.videos.every(video)&&typeof p.cancelled==='boolean'&&integer(p.elapsedMs);case prefix+'SCAN_ERROR':return exact(p,['code'])&&S.codes.includes(p.code);default:return false;}
  }catch{return false;}}
  const message=(channel,type,scanId,payload={})=>({version:5,channel,type:prefix+type,scanId,payload});
  const api=Object.freeze({valid,message,video,diagnostic});root.KurukinProtocol=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
