/* Isolated relay: panel sees public metadata/status only; MAIN owns TikTok URLs. */
(function(root){
  'use strict';
  function createSidebar(doc,runtime,onClose=()=>{}){let container=null,iframe=null;function close(){onClose();container?.remove();container=iframe=null;doc.body.classList.remove('kurukin-panel-open');}function open(){if(container?.isConnected)return iframe;container=doc.createElement('aside');container.id='kurukin-container';iframe=doc.createElement('iframe');iframe.id='kurukin-panel';iframe.title='Kurukin TikTok Collector';iframe.src=runtime.getURL('panel/index.html');container.appendChild(iframe);doc.body.prepend(container);doc.body.classList.add('kurukin-panel-open');return iframe;}return {open,close,toggle:()=>container?.isConnected?close():open(),get frame(){return iframe;}};}
  if(typeof module!=='undefined')module.exports={createSidebar};
  if(!root.chrome?.runtime||!root.document)return;
  const P=root.KurukinProtocol,A=root.KurukinAcquisition,D=root.KurukinAudioDiagnostic,runtime=chrome.runtime,origin='https://www.tiktok.com',extensionOrigin=runtime.getURL('').replace(/\/$/,'');
  let scanId=null,contextId=null,running=false,dead=false,scanVideos=[],reservation=null,current=null,acquiring=false,auto=null,autoRetryTimer=null;
  const postPage=(type,id,payload={})=>window.postMessage(P.message('content',type,id,payload),origin);
  const sendPanel=(type,id,payload)=>sidebar.frame?.contentWindow.postMessage(P.message('content',type,id,payload),extensionOrigin);
  const emptyDiagnostic=()=>({lastErrorStage:null,lastErrorCode:null,fetchMp4Ms:null,decodeMs:null,wavMs:null,handoffMs:null,uploadMs:null});
  const reportAuto=event=>auto&&runtime.id?runtime.sendMessage({type:'KURUKIN_AUTO_EVENT',event}).catch(()=>null):Promise.resolve(null);
  const counters=()=>({eligible:0,reserved:0,transferred:0,accepted:0,failed:0,released:0,state:'idle'});
  const reportEnrichment=metrics=>metrics&&auto&&auto.scanId===scanId?reportAuto({type:'ENRICHMENT',...metrics}):Promise.resolve(null);
  const reportAcquisition=(patch={})=>{if(!auto||auto.scanId!==scanId)return Promise.resolve(null);Object.assign(auto.acquisition,patch);auto.acquiredCount=auto.acquisition.accepted;return reportAuto({type:'ACQUISITION',analysis_id:auto.analysisId,processed_count:auto.discoveredCount||0,acquired_count:auto.acquiredCount,...auto.acquisition});};
  const state=(phase,currentVideoId=null,lastStatus=null,lastUploadMs=null)=>{const payload={requested:reservation?.requests.length||0,uploaded:reservation?.uploaded||0,failed:reservation?.failed||0,released:reservation?.released||0,currentVideoId,lastStatus,lastUploadMs,...(reservation?.audioDiagnostic||emptyDiagnostic()),phase};sendPanel('ACQUISITION_STATE',scanId,payload);if(auto&&auto.scanId===scanId){if(phase==='reserved'||phase==='acquiring'||phase==='secured'||phase==='failed')void reportAuto({type:phase==='reserved'?'INTERLEAVING':'PROGRESS',analysis_id:reservation?.analysisId||null,processed_count:auto.discoveredCount||0,acquired_count:auto.acquiredCount||0});if((phase==='complete'||phase==='exhausted')&&auto.discoveryComplete)void reportAuto({type:'DRAINING',processed_count:auto.discoveredCount||0});}};
  const recordAudioDiagnostic=(failure,timings)=>{if(!reservation)return;reservation.audioDiagnostic={...timings,lastErrorStage:failure.stage,lastErrorCode:failure.code};};
  const recordTimings=timings=>{if(!reservation)return;reservation.audioDiagnostic={...(reservation.audioDiagnostic||emptyDiagnostic()),...timings};};
  const clean=()=>{acquiring=false;current=null;reservation=null;scanVideos=[];};
  const clearAutoRetry=()=>{if(autoRetryTimer){clearTimeout(autoRetryTimer);autoRetryTimer=null;}};
  const sidebar=createSidebar(document,runtime,()=>{const autoActive=!!auto&&auto.scanId===scanId&&(running||acquiring||!!current||!!reservation);if(autoActive)return;if(running&&scanId)postPage('SCAN_CANCEL',scanId);clean();scanId=contextId=null;running=false;});
  function alive(){try{if(!runtime.id)throw Error();return !dead;}catch{dead=true;sidebar.close();window.removeEventListener('message',relay);return false;}}
  const backendError=error=>({code:['BACKEND_REJECTED','RESERVATION_REQUIRED'].includes(error?.code)?error.code:'BACKEND_UNAVAILABLE',diagnostic:A.diagnostic(error)});
  function reservationState(response){let resolve;return {...response,uploaded:0,failed:0,released:0,audioDiagnostic:emptyDiagnostic(),complete:false,empty:response.requests.length===0,done:new Promise(next=>{resolve=next;}),resolveDone:()=>resolve?.()};}
  async function reserve(refresh=false){if(reservation&&!refresh)return reservation;if(!scanVideos.length)throw Object.assign(Error(),{code:'BACKEND_REJECTED'});const response=await A.reserve(runtime,scanVideos);reservation=reservationState(response);state(reservation.empty?'exhausted':'reserved');return reservation;}
  function requestNext(){if(!reservation||current)return;if(auto?.paused)return;const request=reservation.queue.shift();if(!request){acquiring=false;reservation.complete=true;state('complete');reservation.resolveDone?.();if(auto?.draining)void drainAuto();return;}current={videoId:request.tiktok_id,experimental:false};state('acquiring',current.videoId);postPage('AUDIO_REQUEST',scanId,{videoId:current.videoId,experimental:false,extensionBase:runtime.getURL('')});}
  async function startAcquisition(targetId=null){try{await reserve();if(reservation.empty)return;if(targetId&&!reservation.requests.some(r=>r.tiktok_id===targetId))throw Object.assign(Error(),{code:'RESERVATION_REQUIRED'});if(acquiring||current)return;acquiring=true;reservation.queue=targetId?[reservation.requests.find(r=>r.tiktok_id===targetId)]:[...reservation.requests];requestNext();}catch(error){sendPanel('ACQUISITION_ERROR',scanId,backendError(error));}}
  async function startAutoAcquisition(response){try{if(acquiring||current||!response)return false;reservation=reservationState(response);const count=reservation.requests.length;await reportAcquisition({eligible:auto.acquisition.eligible+count,reserved:auto.acquisition.reserved+count,state:count?'reserved':'idle'});if(reservation.empty){state('exhausted');return true;}acquiring=true;reservation.queue=[...reservation.requests];await reportAuto({type:'INTERLEAVING',analysis_id:reservation.analysisId,acquired_count:auto.acquiredCount});requestNext();await reservation.done;return true;}catch(error){await reportAuto({type:error?.code==='BACKEND_UNAVAILABLE'?'WAITING':'ERROR',error:error?.code||'BACKEND_UNAVAILABLE'});return false;}}
  async function drainAuto(){if(!auto||!auto.discoveryComplete||acquiring||current)return;try{const response=await A.nextBatch(runtime,auto.analysisId,auto.finalCorpusAvailable);await reportEnrichment(response.enrichment);if(!response.requests.length){await reportAuto({type:'COMPLETE',processed_count:auto.discoveredCount||0,acquired_count:auto.acquiredCount||0});return;}await startAutoAcquisition(response);}catch(error){await reportAuto({type:error?.code==='BACKEND_UNAVAILABLE'?'WAITING':'ERROR',error:error?.code||'BACKEND_UNAVAILABLE'});}}
  async function checkpointAuto(payload){
    if(!auto||payload.videos.length===0)return false;
    auto.discoveredCount=payload.discoveredCount;auto.lastHasMore=payload.hasMore;auto.finalCorpusAvailable=auto.finalCorpusAvailable||payload.hasMore===false;
    const event={type:'CHECKPOINT',analysis_id:auto.analysisId,scan_id:auto.scanId,target:auto.target,discovered_count:payload.discoveredCount,checkpoint_count:payload.checkpointCount,checkpoint_number:payload.checkpointNumber,resume_state:payload.resume,has_more:payload.hasMore,scan_complete:payload.complete};
    await reportAuto(event); // Durable browser checkpoint always precedes the HTTP delivery.
    try{const first=payload.videos[0],saved=await A.checkpoint(runtime,{analysis_id:auto.analysisId,scan_id:auto.scanId,checkpoint_number:payload.checkpointNumber,checkpoint_count:payload.checkpointCount,discovered_count:payload.discoveredCount,target:auto.target,has_more:payload.hasMore,profile:{username:auto.channel,nickname:first.nickname},videos:payload.videos});if(saved.analysisId!==auto.analysisId)throw Object.assign(Error(),{code:'BACKEND_REJECTED'});await reportEnrichment(saved.enrichment);await reportAuto({type:'CHECKPOINT_SAVED',checkpoint_count:payload.checkpointCount,discovered_count:payload.discoveredCount});const batch=await A.nextBatch(runtime,auto.analysisId,false);if(batch.analysisId!==auto.analysisId)throw Object.assign(Error(),{code:'BACKEND_REJECTED'});await reportEnrichment(batch.enrichment);await startAutoAcquisition(batch);return true;}catch(error){auto.checkpointBackpressure=error?.code==='BACKEND_UNAVAILABLE';await reportAuto({type:auto.checkpointBackpressure?'WAITING':'ERROR',error:error?.code||'BACKEND_UNAVAILABLE'});return false;}
  }
  const needsUser=code=>['DIRECT_CHALLENGE','DIRECT_LOGIN_REQUIRED','DIRECT_403','DIRECT_429'].includes(code);
  function retryAutoOpening(){if(!auto)return;clearAutoRetry();auto.openingAttempts=(auto.openingAttempts||0)+1;if(auto.openingAttempts>4){reportAuto({type:'ERROR',error:'PROFILE_HYDRATION_TIMEOUT'});return;}autoRetryTimer=setTimeout(()=>{autoRetryTimer=null;if(auto)postPage('CONTEXT_GET',auto.contextId);},1000);}
  function runAuto(channel){if(!channel||typeof channel.id!=='string'||typeof channel.channel!=='string'||!(channel.target==='full'||Number.isSafeInteger(channel.target)))return;clearAutoRetry();clean();const prior=channel.acquisition&&typeof channel.acquisition==='object'?channel.acquisition:{};auto={channelId:channel.id,channel:channel.channel.toLowerCase(),target:channel.target,contextId:crypto.randomUUID(),analysisId:channel.analysisId||crypto.randomUUID(),scanId:channel.scanId||crypto.randomUUID(),resume:channel.resume||null,discoveredCount:channel.resume?.discoveredCount||0,acquiredCount:Number.isSafeInteger(prior.accepted)?prior.accepted:0,acquisition:{...counters(),...prior},openingAttempts:0,discoveryComplete:false,finalCorpusAvailable:channel.has_more===false,draining:false};postPage('CONTEXT_GET',auto.contextId);}
  const browserFailureCode=failure=>({FETCH_MP4:failure.code==='VIDEO_NOT_AVAILABLE'?'FETCH_MP4_VIDEO_NOT_AVAILABLE':'FETCH_MP4_FAILED',DECODE_AUDIO:'DECODE_FAILED',RESAMPLE_PCM:'DECODE_FAILED',ENCODE_WAV:'WAV_FAILED',HANDOFF_WAV:'HANDOFF_FAILED',HTTP_UPLOAD:'HTTP_UPLOAD_FAILED'}[failure.stage]||null);
  async function failCurrent(id,failure,timings,lastStatus=0,lastUploadMs=null){reservation.failed++;if(auto)await reportAcquisition({failed:auto.acquisition.failed+1,state:'failed'});recordAudioDiagnostic(failure,timings);current=null;state('failed',id,lastStatus,lastUploadMs);const code=browserFailureCode(failure);try{if(code&&(await A.reportFailure(runtime,reservation.analysisId,id,code)).released){reservation.released++;if(auto)await reportAcquisition({released:auto.acquisition.released+1,state:'released'});state('failed',id,lastStatus,lastUploadMs);}}catch{/* The counter remains unreleased; a later browser report may safely retry. */}finally{requestNext();}}
  async function uploadCurrent(buffer,meta){const item=current;item.timings=D.timings(meta);try{const result=await A.upload(runtime,reservation.analysisId,item.videoId,buffer),timings=D.timings(meta,result.handoffMs,result.uploadMs);recordTimings(timings);if(result.status===202){reservation.uploaded++;if(auto)await reportAcquisition({accepted:auto.acquisition.accepted+1,state:'accepted'});state('secured',item.videoId,202,result.uploadMs);current=null;requestNext();}else await failCurrent(item.videoId,D.fromUploadError(),timings,result.status,result.uploadMs);}catch(error){const timings=D.timings(meta,error?.handoffMs,error?.uploadMs);await failCurrent(item.videoId,D.fromUploadError(error),timings,0,error?.uploadMs??null);}finally{buffer=null;}}
  function relay(event){if(!alive())return;const m=event.data;
    if(event.source===sidebar.frame?.contentWindow&&event.origin===extensionOrigin&&P.valid(m,'panel')){switch(m.type){case 'KURUKIN_PANEL_READY':contextId=m.scanId;postPage('CONTEXT_GET',contextId);break;case 'KURUKIN_PANEL_CLOSE':sidebar.close();break;case 'KURUKIN_SCAN_START':if(!running){clean();scanId=m.scanId;running=true;postPage('SCAN_START',scanId,m.payload);}break;case 'KURUKIN_ACQUISITION_PREPARE':if(!running&&m.scanId===scanId)reserve(!!(reservation?.complete||reservation?.empty)).catch(error=>sendPanel('ACQUISITION_ERROR',scanId,backendError(error)));break;case 'KURUKIN_ACQUISITION_START':if(!running&&m.scanId===scanId)startAcquisition();break;case 'KURUKIN_ACQUISITION_TARGET':if(!running&&m.scanId===scanId)startAcquisition(m.payload.videoId);break;case 'KURUKIN_EXPERIMENTAL_AUDIO_REQUEST':if(!running&&!acquiring&&m.scanId===scanId){current={videoId:m.payload.videoId,experimental:true};postPage('AUDIO_REQUEST',scanId,{videoId:current.videoId,experimental:true,extensionBase:runtime.getURL('')});}break;case 'KURUKIN_SCAN_CANCEL':if(m.scanId===scanId&&running)postPage('SCAN_CANCEL',scanId);break;}}
    else if(event.source===window&&event.origin===origin&&P.valid(m,'page')){if(m.type==='KURUKIN_CONTEXT'&&m.scanId===contextId){sendPanel('CONTEXT',contextId,m.payload);return;}if(m.type==='KURUKIN_CONTEXT'&&m.scanId===auto?.contextId){if(!m.payload.loggedIn){void reportAuto({type:'NEEDS_USER',error:'TikTok login required'});return;}if(m.payload.username?.toLowerCase()!==auto.channel){void reportAuto({type:'REOPEN'});return;}clearAutoRetry();scanId=auto.scanId;running=true;void reportAuto({type:'SCANNING',scan_target:auto.target,analysis_id:auto.analysisId,scan_id:auto.scanId,resume_state:auto.resume});postPage('SCAN_START',scanId,auto.resume?{target:auto.target,resume:auto.resume}:{target:auto.target});return;}if(m.scanId!==scanId)return;if(m.type==='KURUKIN_SCAN_CHECKPOINT'&&auto?.scanId===scanId){void checkpointAuto(m.payload).then(accepted=>postPage('SCAN_CHECKPOINT_ACK',scanId,{checkpointNumber:m.payload.checkpointNumber,accepted}));return;}if(['KURUKIN_SCAN_PROGRESS','KURUKIN_SCAN_COMPLETE','KURUKIN_SCAN_ERROR'].includes(m.type)&&running){if(m.type==='KURUKIN_SCAN_PROGRESS'&&auto?.scanId===scanId)void reportAuto({type:'PROGRESS',processed_count:m.payload.total});if(m.type!=='KURUKIN_SCAN_PROGRESS')running=false;if(m.type==='KURUKIN_SCAN_COMPLETE'&&!m.payload.cancelled){scanVideos=m.payload.videos;if(auto){auto.discoveryComplete=true;auto.draining=true;void reportAuto({type:'DRAINING',processed_count:auto.discoveredCount||scanVideos.length});void drainAuto();}}else if(m.type==='KURUKIN_SCAN_ERROR'){if(m.payload.code==='DIRECT_TARGET_MISSING')retryAutoOpening();else if(!auto?.checkpointBackpressure)void reportAuto({type:needsUser(m.payload.code)?'NEEDS_USER':'ERROR',error:m.payload.code});}sendPanel(m.type.slice('KURUKIN_'.length),scanId,m.payload);return;}if(!current||m.payload.videoId!==current.videoId)return;if(m.type==='KURUKIN_AUDIO_READY'){if(current.experimental){sendPanel('EXPERIMENTAL_AUDIO_RESULT',scanId,{videoId:current.videoId,sileroMs:m.payload.sileroMs||0,yamnetMs:m.payload.yamnetMs||0,audioClassification:m.payload.audio_classification||null});current=null;}else uploadCurrent(m.payload.buffer,m.payload);return;}if(m.type==='KURUKIN_AUDIO_ERROR'&&m.payload.terminal){if(current.experimental){current=null;sendPanel('ACQUISITION_ERROR',scanId,{code:'AUDIO_UPLOAD_FAILED',diagnostic:A.diagnostic()});}else{const id=current.videoId;void failCurrent(id,D.fromAudioError(m.payload),D.timings(m.payload));}}}
  }
  window.addEventListener('message',relay);runtime.onMessage.addListener(message=>{if(!alive())return;if(message?.type==='KURUKIN_PANEL_TOGGLE'&&Object.keys(message).length===1)sidebar.toggle();if(message?.type==='KURUKIN_AUTO_RUN'&&Object.keys(message).length===2)runAuto(message.channel);if(message?.type==='KURUKIN_AUTO_TRANSFERRED'&&Object.keys(message).length===2&&current?.videoId===message.videoId&&auto)void reportAcquisition({transferred:auto.acquisition.transferred+1,state:'worker_handoff_confirmed'});if(message?.type==='KURUKIN_AUTO_PAUSE'&&Object.keys(message).length===1&&auto){auto.paused=true;clearAutoRetry();if(running&&scanId)postPage('SCAN_CANCEL',scanId);}});runtime.sendMessage({type:'KURUKIN_AUTO_EVENT',event:{type:'READY'}}).catch(()=>{});window.addEventListener('pagehide',()=>{clearAutoRetry();if(running&&scanId)postPage('SCAN_CANCEL',scanId);clean();});
})(globalThis);
