/* Isolated relay: panel sees public metadata/status only; MAIN owns TikTok URLs. */
(function(root){
  'use strict';
  function createSidebar(doc,runtime,onClose=()=>{}){let container=null,iframe=null;function close(){onClose();container?.remove();container=iframe=null;doc.body.classList.remove('kurukin-panel-open');}function open(){if(container?.isConnected)return iframe;container=doc.createElement('aside');container.id='kurukin-container';iframe=doc.createElement('iframe');iframe.id='kurukin-panel';iframe.title='Kurukin TikTok Collector';iframe.src=runtime.getURL('panel/index.html');container.appendChild(iframe);doc.body.prepend(container);doc.body.classList.add('kurukin-panel-open');return iframe;}return {open,close,toggle:()=>container?.isConnected?close():open(),get frame(){return iframe;}};}
  if(typeof module!=='undefined')module.exports={createSidebar};
  if(!root.chrome?.runtime||!root.document)return;
  const P=root.KurukinProtocol,A=root.KurukinAcquisition,D=root.KurukinAudioDiagnostic,runtime=chrome.runtime,origin='https://www.tiktok.com',extensionOrigin=runtime.getURL('').replace(/\/$/,'');
  let scanId=null,contextId=null,running=false,dead=false,scanVideos=[],reservation=null,current=null,acquiring=false,auto=null;
  const postPage=(type,id,payload={})=>window.postMessage(P.message('content',type,id,payload),origin);
  const sendPanel=(type,id,payload)=>sidebar.frame?.contentWindow.postMessage(P.message('content',type,id,payload),extensionOrigin);
  const emptyDiagnostic=()=>({lastErrorStage:null,lastErrorCode:null,fetchMp4Ms:null,decodeMs:null,wavMs:null,handoffMs:null,uploadMs:null});
  const reportAuto=event=>{if(auto&&runtime.id)runtime.sendMessage({type:'KURUKIN_AUTO_EVENT',event}).catch(()=>{});};
  const state=(phase,currentVideoId=null,lastStatus=null,lastUploadMs=null)=>{const payload={requested:reservation?.requests.length||0,uploaded:reservation?.uploaded||0,failed:reservation?.failed||0,released:reservation?.released||0,currentVideoId,lastStatus,lastUploadMs,...(reservation?.audioDiagnostic||emptyDiagnostic()),phase};sendPanel('ACQUISITION_STATE',scanId,payload);if(auto&&auto.scanId===scanId){if(phase==='reserved'||phase==='acquiring'||phase==='secured'||phase==='failed')reportAuto({type:phase==='reserved'?'ACQUIRING':'PROGRESS',analysis_id:reservation?.analysisId||null,processed_count:payload.requested,acquired_count:payload.uploaded});if(phase==='complete'||phase==='exhausted')reportAuto({type:'COMPLETE',processed_count:payload.requested,acquired_count:payload.uploaded});}};
  const recordAudioDiagnostic=(failure,timings)=>{if(!reservation)return;reservation.audioDiagnostic={...timings,lastErrorStage:failure.stage,lastErrorCode:failure.code};};
  const recordTimings=timings=>{if(!reservation)return;reservation.audioDiagnostic={...(reservation.audioDiagnostic||emptyDiagnostic()),...timings};};
  const clean=()=>{acquiring=false;current=null;reservation=null;scanVideos=[];};
  const sidebar=createSidebar(document,runtime,()=>{const autoActive=!!auto&&auto.scanId===scanId&&(running||acquiring||!!current||!!reservation);if(autoActive)return;if(running&&scanId)postPage('SCAN_CANCEL',scanId);clean();scanId=contextId=null;running=false;});
  function alive(){try{if(!runtime.id)throw Error();return !dead;}catch{dead=true;sidebar.close();window.removeEventListener('message',relay);return false;}}
  const backendError=error=>({code:['BACKEND_REJECTED','RESERVATION_REQUIRED'].includes(error?.code)?error.code:'BACKEND_UNAVAILABLE',diagnostic:A.diagnostic(error)});
  async function reserve(refresh=false){if(reservation&&!refresh)return reservation;if(!scanVideos.length)throw Object.assign(Error(),{code:'BACKEND_REJECTED'});const response=await A.reserve(runtime,scanVideos);reservation={...response,uploaded:0,failed:0,released:0,audioDiagnostic:emptyDiagnostic(),complete:false,empty:response.requests.length===0};state(reservation.empty?'exhausted':'reserved');return reservation;}
  function requestNext(){if(!reservation||current)return;if(auto?.paused)return;const request=reservation.queue.shift();if(!request){acquiring=false;reservation.complete=true;state('complete');return;}current={videoId:request.tiktok_id,experimental:false};state('acquiring',current.videoId);postPage('AUDIO_REQUEST',scanId,{videoId:current.videoId,experimental:false,extensionBase:runtime.getURL('')});}
  async function startAcquisition(targetId=null){try{await reserve();if(reservation.empty)return;if(targetId&&!reservation.requests.some(r=>r.tiktok_id===targetId))throw Object.assign(Error(),{code:'RESERVATION_REQUIRED'});if(acquiring||current)return;acquiring=true;reservation.queue=targetId?[reservation.requests.find(r=>r.tiktok_id===targetId)]:[...reservation.requests];requestNext();}catch(error){sendPanel('ACQUISITION_ERROR',scanId,backendError(error));}}
  async function startAutoAcquisition(){try{await reserve();if(reservation.empty)return;if(acquiring||current)return;acquiring=true;reservation.queue=[...reservation.requests];reportAuto({type:'ACQUIRING',analysis_id:reservation.analysisId,processed_count:reservation.requests.length,acquired_count:0});requestNext();}catch(error){reportAuto({type:error?.code==='BACKEND_UNAVAILABLE'?'WAITING':'ERROR',error:error?.code||'BACKEND_UNAVAILABLE'});}}
  const needsUser=code=>['DIRECT_CHALLENGE','DIRECT_LOGIN_REQUIRED','DIRECT_403','DIRECT_429','DIRECT_TARGET_MISSING'].includes(code);
  function runAuto(channel){if(!channel||typeof channel.id!=='string'||typeof channel.channel!=='string'||!Number.isSafeInteger(channel.target))return;clean();auto={channelId:channel.id,channel:channel.channel.toLowerCase(),target:channel.target,contextId:crypto.randomUUID(),scanId:null};postPage('CONTEXT_GET',auto.contextId);}
  const browserFailureCode=failure=>({FETCH_MP4:failure.code==='VIDEO_NOT_AVAILABLE'?'FETCH_MP4_VIDEO_NOT_AVAILABLE':'FETCH_MP4_FAILED',DECODE_AUDIO:'DECODE_FAILED',RESAMPLE_PCM:'DECODE_FAILED',ENCODE_WAV:'WAV_FAILED',HANDOFF_WAV:'HANDOFF_FAILED',HTTP_UPLOAD:'HTTP_UPLOAD_FAILED'}[failure.stage]||null);
  async function failCurrent(id,failure,timings,lastStatus=0,lastUploadMs=null){reservation.failed++;recordAudioDiagnostic(failure,timings);current=null;state('failed',id,lastStatus,lastUploadMs);const code=browserFailureCode(failure);try{if(code&&(await A.reportFailure(runtime,reservation.analysisId,id,code)).released){reservation.released++;state('failed',id,lastStatus,lastUploadMs);}}catch{/* The counter remains unreleased; a later browser report may safely retry. */}finally{requestNext();}}
  async function uploadCurrent(buffer,meta){const item=current;item.timings=D.timings(meta);try{const result=await A.upload(runtime,reservation.analysisId,item.videoId,buffer),timings=D.timings(meta,result.handoffMs,result.uploadMs);recordTimings(timings);if(result.status===202){reservation.uploaded++;state('secured',item.videoId,202,result.uploadMs);current=null;requestNext();}else await failCurrent(item.videoId,D.fromUploadError(),timings,result.status,result.uploadMs);}catch(error){const timings=D.timings(meta,error?.handoffMs,error?.uploadMs);await failCurrent(item.videoId,D.fromUploadError(error),timings,0,error?.uploadMs??null);}finally{buffer=null;}}
  function relay(event){if(!alive())return;const m=event.data;
    if(event.source===sidebar.frame?.contentWindow&&event.origin===extensionOrigin&&P.valid(m,'panel')){switch(m.type){case 'KURUKIN_PANEL_READY':contextId=m.scanId;postPage('CONTEXT_GET',contextId);break;case 'KURUKIN_PANEL_CLOSE':sidebar.close();break;case 'KURUKIN_SCAN_START':if(!running){clean();scanId=m.scanId;running=true;postPage('SCAN_START',scanId,m.payload);}break;case 'KURUKIN_ACQUISITION_PREPARE':if(!running&&m.scanId===scanId)reserve(!!(reservation?.complete||reservation?.empty)).catch(error=>sendPanel('ACQUISITION_ERROR',scanId,backendError(error)));break;case 'KURUKIN_ACQUISITION_START':if(!running&&m.scanId===scanId)startAcquisition();break;case 'KURUKIN_ACQUISITION_TARGET':if(!running&&m.scanId===scanId)startAcquisition(m.payload.videoId);break;case 'KURUKIN_EXPERIMENTAL_AUDIO_REQUEST':if(!running&&!acquiring&&m.scanId===scanId){current={videoId:m.payload.videoId,experimental:true};postPage('AUDIO_REQUEST',scanId,{videoId:current.videoId,experimental:true,extensionBase:runtime.getURL('')});}break;case 'KURUKIN_SCAN_CANCEL':if(m.scanId===scanId&&running)postPage('SCAN_CANCEL',scanId);break;}}
    else if(event.source===window&&event.origin===origin&&P.valid(m,'page')){if(m.type==='KURUKIN_CONTEXT'&&m.scanId===contextId){sendPanel('CONTEXT',contextId,m.payload);return;}if(m.type==='KURUKIN_CONTEXT'&&m.scanId===auto?.contextId){if(!m.payload.loggedIn||m.payload.username?.toLowerCase()!==auto.channel){reportAuto({type:'NEEDS_USER',error:!m.payload.loggedIn?'TikTok login required':'Unexpected TikTok profile or interstitial'});return;}scanId=crypto.randomUUID();auto.scanId=scanId;running=true;reportAuto({type:'SCANNING'});postPage('SCAN_START',scanId,{target:auto.target});return;}if(m.scanId!==scanId)return;if(['KURUKIN_SCAN_PROGRESS','KURUKIN_SCAN_COMPLETE','KURUKIN_SCAN_ERROR'].includes(m.type)&&running){if(m.type!=='KURUKIN_SCAN_PROGRESS')running=false;if(m.type==='KURUKIN_SCAN_COMPLETE'&&!m.payload.cancelled){scanVideos=m.payload.videos;reportAuto({type:'SCAN_COMPLETE',scan_id:scanId,processed_count:scanVideos.length});void startAutoAcquisition();}else if(m.type==='KURUKIN_SCAN_ERROR')reportAuto({type:needsUser(m.payload.code)?'NEEDS_USER':'ERROR',error:m.payload.code});sendPanel(m.type.slice('KURUKIN_'.length),scanId,m.payload);return;}if(!current||m.payload.videoId!==current.videoId)return;if(m.type==='KURUKIN_AUDIO_READY'){if(current.experimental){sendPanel('EXPERIMENTAL_AUDIO_RESULT',scanId,{videoId:current.videoId,sileroMs:m.payload.sileroMs||0,yamnetMs:m.payload.yamnetMs||0,audioClassification:m.payload.audio_classification||null});current=null;}else uploadCurrent(m.payload.buffer,m.payload);return;}if(m.type==='KURUKIN_AUDIO_ERROR'&&m.payload.terminal){if(current.experimental){current=null;sendPanel('ACQUISITION_ERROR',scanId,{code:'AUDIO_UPLOAD_FAILED',diagnostic:A.diagnostic()});}else{const id=current.videoId;void failCurrent(id,D.fromAudioError(m.payload),D.timings(m.payload));}}}
  }
  window.addEventListener('message',relay);runtime.onMessage.addListener(message=>{if(!alive())return;if(message?.type==='KURUKIN_PANEL_TOGGLE'&&Object.keys(message).length===1)sidebar.toggle();if(message?.type==='KURUKIN_AUTO_RUN'&&Object.keys(message).length===2)runAuto(message.channel);if(message?.type==='KURUKIN_AUTO_PAUSE'&&Object.keys(message).length===1&&auto){auto.paused=true;if(running&&scanId)postPage('SCAN_CANCEL',scanId);}});runtime.sendMessage({type:'KURUKIN_AUTO_EVENT',event:{type:'READY'}}).catch(()=>{});window.addEventListener('pagehide',()=>{if(running&&scanId)postPage('SCAN_CANCEL',scanId);clean();});
})(globalThis);
