const {test}=require('node:test'),assert=require('node:assert/strict');
const A=require('../page/audio.js');
const raw=()=>({video:{duration:1,playAddr:'https://cdn.test/video?token=never-crosses'}});
const audio=()=>({numberOfChannels:1,length:4,sampleRate:16000,duration:4/16000,getChannelData:()=>new Float32Array([0,.1,-.1,0])});
function harness(){const signal=new AbortController(),events=[];const env={setTimeout,clearTimeout,fetch:async()=>({ok:true,status:200,headers:{get:key=>key==='content-type'?'video/mp4':'4'},arrayBuffer:async()=>new ArrayBuffer(4)}),AudioContext:class{async decodeAudioData(){return audio();}async close(){}},OfflineAudioContext:class{createBuffer(){return {copyToChannel(){}}}createBufferSource(){return {connect(){},start(){},disconnect(){}}}async startRendering(){return audio();}}};return {signal,events,env};}
test('normal acquisition does not call Silero or YAMNet and reports only acquisition timings',async()=>{const h=harness(),speech={analyze:()=>assert.fail('Silero must not run')},classifier={analyze:()=>assert.fail('YAMNet must not run')};const result=await A.extract('12345',{media:new Map([['12345',{duration:1,candidates:A.candidates(raw())}]]),signal:h.signal.signal,emit:(type,payload)=>h.events.push({type,payload}),env:h.env,speech,classifier});assert.equal(Buffer.from(result.buffer,0,4).toString(),'RIFF');assert.deepEqual(Object.keys(result.meta).filter(k=>/silero|yamnet|classification/i.test(k)),[]);assert.ok(h.events.every(e=>e.type!=='AUDIO_SCREENING'));for(const key of ['fetchMp4Ms','decodeResampleMs','wavEncodeMs','totalAcquisitionMs'])assert.ok(Number.isSafeInteger(result.meta[key]));});
test('PCM and WAV temporary references are cleared after the transfer-ready result',async()=>{const h=harness(),result=await A.extract('12345',{media:new Map([['12345',{duration:1,candidates:A.candidates(raw())}]]),signal:h.signal.signal,env:h.env});assert.equal(result.buffer.byteLength,52);assert.doesNotMatch(A.extract.toString(),/speech\.analyze|classifier\.analyze|KurukinSpeech|KurukinAudioClassifier/);});
test('audio stages that never run have no timing value',async()=>{const h=harness();await assert.rejects(A.extract('99999',{media:new Map(),signal:h.signal.signal,emit:(type,payload)=>h.events.push({type,payload}),env:h.env}),{code:'VIDEO_NOT_AVAILABLE_IN_CURRENT_SCAN'});const event=h.events.find(e=>e.type==='AUDIO_ERROR');assert.equal(event.payload.fetchMp4Ms,null);assert.equal(event.payload.decodeResampleMs,null);assert.equal(event.payload.wavEncodeMs,null);});
test('experimental path is separate and is the only code path that invokes classifiers',async()=>{assert.match(A.extractExperimental.toString(),/KurukinSpeech\.analyze/);assert.match(A.extractExperimental.toString(),/KurukinAudioClassifier\.analyze/);assert.doesNotMatch(A.extract.toString(),/AUDIO_SCREENING|KurukinSpeech|KurukinAudioClassifier/);});
test('media candidates remain MAIN-only values and canonical helpers do not expose them',()=>{const candidate=A.candidates(raw())[0];assert.match(candidate.url,/token=/);assert.equal(A.candidates({video:{playAddr:'javascript:bad'}}).length,0);assert.equal(A.wav(new Float32Array([0])).byteLength,46);});
