const {test}=require('node:test'),assert=require('node:assert/strict');
const A=require('../lib/auto-curator.js');
function fixture(){let value,clock=1_700_000_000_000;const calls=[];const storage={get:async()=>value,set:async(_key,next)=>{value=JSON.parse(JSON.stringify(next));}};const tabs={navigate:async(tab,url)=>calls.push(['navigate',tab,url]),run:async(tab,c)=>calls.push(['run',tab,c.channel]),pause:async tab=>calls.push(['pause',tab])};const alarms={create:async(name,info)=>calls.push(['alarm',name,info.when])};return {storage,tabs,alarms,calls,now:()=>clock,advance:ms=>clock+=ms,get state(){return value;},make:id=>A.create({storage,tabs,alarms,now:()=>clock,instanceId:id})};}
test('queue normalizes profile URLs and deduplicates channels',()=>{assert.deepEqual(A.normalize([' @Creator.1 ','https://www.tiktok.com/@creator.1/','creator2','not/a/profile']).map(x=>x.channel),['creator.1','creator2']);});
test('state transitions retain the required per-channel counters',()=>{let state=A.queue(['@one'],7,()=>100);state.active_channel_id=state.channels[0].id;state=A.transition(state,{type:'SCANNING'},()=>101);state=A.transition(state,{type:'SCAN_COMPLETE',scan_id:'scan-1',processed_count:12},()=>102);state=A.transition(state,{type:'ACQUIRING',analysis_id:'analysis-1',acquired_count:3},()=>103);assert.equal(state.channels[0].status,'acquiring');assert.equal(state.channels[0].analysis_id,'analysis-1');assert.equal(state.channels[0].processed_count,12);assert.equal(state.channels[0].acquired_count,3);});
test('one channel at a time navigates only the first pending channel',async()=>{const f=fixture(),o=f.make('one');await o.start(['@one','@two'],9);assert.deepEqual(f.calls,[['navigate',9,'https://www.tiktok.com/@one']]);assert.equal(f.state.active_channel_id,f.state.channels[0].id);});
test('pause resume preserves the queue and runs the same active channel safely',async()=>{const f=fixture(),o=f.make('one');await o.start(['@one','@two'],9);await o.pause();assert.equal(f.state.status,'paused');assert.equal(f.state.channels[0].status,'paused');assert.ok(f.calls.some(call=>call[0]==='pause'));await o.resume();assert.equal(f.state.status,'running');assert.equal(f.state.channels[0].status,'opening');assert.ok(f.calls.some(call=>call[0]==='run'&&call[2]==='one'));});
test('stop keeps the queue intact and prevents further navigation',async()=>{const f=fixture(),o=f.make('one');await o.start(['@one','@two'],9);await o.stop();const before=f.calls.length;await o.tick();assert.equal(f.state.status,'stopped');assert.equal(f.state.channels.length,2);assert.equal(f.calls.length,before);});
test('skip current moves safely to the next pending channel',async()=>{const f=fixture(),o=f.make('one');await o.start(['@one','@two'],9);await o.skip();assert.equal(f.state.channels[0].status,'skipped');assert.equal(f.state.active_channel_id,f.state.channels[1].id);assert.deepEqual(f.calls.at(-1),['navigate',9,'https://www.tiktok.com/@two']);});
test('restore from storage resumes an opening channel without recreating the queue',async()=>{const f=fixture(),first=f.make('first');await first.start(['@one'],9);f.advance(A.LOCK_MS+1);const restored=f.make('restored');await restored.ready(9);assert.equal(f.state.channels.length,1);assert.ok(f.calls.some(call=>call[0]==='run'&&call[2]==='one'));});
test('completed channel is never automatically rerun',async()=>{const f=fixture(),o=f.make('one');await o.start(['@one'],9);await o.event({type:'COMPLETE',processed_count:10,acquired_count:4});const before=f.calls.length;await o.tick();assert.equal(f.state.status,'completed');assert.equal(f.state.channels[0].status,'completed');assert.equal(f.calls.length,before);});
test('needs user pauses the queue with a clear channel state',async()=>{const f=fixture(),o=f.make('one');await o.start(['@one'],9);await o.event({type:'NEEDS_USER',error:'TikTok login required'});assert.equal(f.state.status,'paused');assert.equal(f.state.channels[0].status,'needs_user');assert.equal(f.state.channels[0].last_error,'TikTok login required');});
test('capacity waiting schedules backoff and then safely retries the same channel',async()=>{const f=fixture(),o=f.make('one');await o.start(['@one'],9);await o.event({type:'WAITING',error:'BACKEND_UNAVAILABLE'});assert.equal(f.state.channels[0].status,'waiting');assert.ok(f.calls.some(call=>call[0]==='alarm'));f.advance(A.RETRY_MS+1);await o.tick();assert.equal(f.state.channels[0].status,'opening');assert.ok(f.calls.some(call=>call[0]==='run'));});
test('a second orchestrator cannot take a live logical lock',async()=>{const f=fixture(),one=f.make('one');await one.start(['@one'],9);const two=f.make('two');assert.equal(await two.tick(),null);assert.equal(f.calls.filter(call=>call[0]==='navigate').length,1);});
test('exhausted completion starts the next channel and an error leaves remaining work intact',async()=>{const f=fixture(),o=f.make('one');await o.start(['@one','@two','@three'],9);await o.event({type:'COMPLETE',processed_count:0,acquired_count:0});assert.equal(f.state.channels[0].status,'completed');assert.equal(f.state.channels[1].status,'opening');await o.event({type:'ERROR',error:'DIRECT_NETWORK'});assert.equal(f.state.channels[1].status,'error');assert.equal(f.state.channels[2].status,'pending');assert.equal(f.state.status,'paused');});
