(()=>{
  'use strict';
  const P=globalThis.KurukinProtocol,N=globalThis.KurukinNormalizer,$=id=>document.getElementById(id),origin='https://www.tiktok.com',contextId=crypto.randomUUID();
  let scanId=null,running=false,loggedIn=false,username=null,videos=[],startedAt=0;
  const send=(type,id,payload={})=>parent.postMessage(P.message('panel',type,id,payload),origin);
  const validId=id=>/^\d{5,30}$/.test(id);
  function controls(){ $('start').disabled=running||!loggedIn||!username;$('targets').disabled=running;$('cancel').hidden=!running;$('copy').disabled=$('download').disabled=running||!videos.length; }
  const ms=value=>Number.isSafeInteger(value)?`${value} ms`:'—';
  function setState(p){$('requested').textContent=p.requested;$('uploaded').textContent=p.uploaded;$('failed').textContent=p.failed;$('released').textContent=p.released;$('current').textContent=p.currentVideoId||'—';$('last-error').textContent=p.lastErrorStage?`${p.lastErrorStage} · ${p.lastErrorCode}`:'—';$('fetch-mp4').textContent=ms(p.fetchMp4Ms);$('decode').textContent=ms(p.decodeMs);$('wav').textContent=ms(p.wavMs);$('handoff').textContent=ms(p.handoffMs);$('upload').textContent=ms(p.uploadMs);$('acquisition-status').textContent={idle:'Reserva requerida.',reserved:'Audio reservado.',exhausted:'No hay más candidatos adquiribles en este análisis.',acquiring:`Adquiriendo audio: ${p.uploaded+p.failed+1} / ${p.requested}`,secured:'Audio secured',failed:p.released===p.failed?'Falló la adquisición y la reserva fue liberada.':'Falló la adquisición; continúa el lote.',complete:'Acquisition completada.'}[p.phase]||'';$('acquire').disabled=p.phase!=='reserved';}
  function reset(){videos=[];$('acquisition').hidden=true;$('acquire').disabled=true;setState({requested:0,uploaded:0,failed:0,released:0,currentVideoId:null,lastStatus:null,lastUploadMs:null,lastErrorStage:null,lastErrorCode:null,fetchMp4Ms:null,decodeMs:null,wavMs:null,handoffMs:null,uploadMs:null,phase:'idle'});}
  $('close').onclick=()=>send('PANEL_CLOSE',contextId);
  const autoRuntime=globalThis.chrome?.runtime,autoStorage=globalThis.chrome?.storage;
  function autoRender(state){if(!state||!$('auto-status'))return;$('auto-status').textContent=`Estado: ${state.status||'idle'}`;const list=$('auto-list');list.replaceChildren();for(const channel of state.channels||[]){const row=document.createElement('div'),name=document.createElement('strong'),detail=document.createElement('span');row.className='auto-row';name.textContent=`@${channel.channel} · ${channel.status}`;detail.textContent=`${channel.acquired_count||0}/${channel.processed_count||0}${channel.last_error?` · ${channel.last_error}`:''}`;row.append(name,detail);list.append(row);}}
  async function autoCommand(type,channels){if(!autoRuntime)return;const response=await autoRuntime.sendMessage({type,...(channels===undefined?{}:{channels})});if(response?.ok)autoRender(response.value);}
  if(autoRuntime&&autoStorage){$('auto-start').onclick=()=>autoCommand('KURUKIN_AUTO_START',$('auto-channels').value);$('auto-pause').onclick=()=>autoCommand('KURUKIN_AUTO_PAUSE');$('auto-resume').onclick=()=>autoCommand('KURUKIN_AUTO_RESUME');$('auto-stop').onclick=()=>autoCommand('KURUKIN_AUTO_STOP');$('auto-skip').onclick=()=>autoCommand('KURUKIN_AUTO_SKIP');autoCommand('KURUKIN_AUTO_GET');autoStorage.local.onChanged.addListener(changes=>{if(changes.kurukin_auto_curator_v1)autoRender(changes.kurukin_auto_curator_v1.newValue);});}
  $('start').onclick=()=>{if(running||!loggedIn||!username)return;reset();scanId=crypto.randomUUID();running=true;startedAt=Date.now();const target=Number(document.querySelector('input[name="target"]:checked').value);$('bar').max=target;$('bar').value=0;$('total').textContent=`0 / ${target} vídeos`;$('status').textContent='Preparando contexto…';$('page').textContent='0';$('http').textContent='—';$('debug').textContent='[]';controls();send('SCAN_START',scanId,{target});};
  $('cancel').onclick=()=>send('SCAN_CANCEL',scanId);$('prepare').onclick=()=>{if(scanId)send('ACQUISITION_PREPARE',scanId);};$('acquire').onclick=()=>{if(scanId)send('ACQUISITION_START',scanId);};$('targeted-acquire').onclick=()=>{const id=$('targeted-id').value.trim();if(validId(id)&&scanId)send('ACQUISITION_TARGET',scanId,{videoId:id});};$('experimental-run').onclick=()=>{const id=$('experimental-id').value.trim();if(validId(id)&&scanId){$('experimental-result').textContent='Cargando modelos experimentales…';send('EXPERIMENTAL_AUDIO_REQUEST',scanId,{videoId:id});}};
  $('copy').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(N.exportVideos(videos),null,2));$('status').textContent='JSON copiado';}catch{$('status').textContent='No se pudo copiar JSON.';}};
  $('download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(N.exportVideos(videos),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='kurukin-videos.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  window.addEventListener('message',event=>{if(event.source!==parent||event.origin!==origin||!P.valid(event.data,'content'))return;const {type,payload:p,scanId:id}=event.data;
    if(type==='KURUKIN_CONTEXT'&&id===contextId){loggedIn=p.loggedIn;username=p.username;$('username').textContent=username?`@${username}`:'Abre un perfil';$('session').textContent=loggedIn?'● Sesión iniciada':'Inicia sesión en TikTok para analizar perfiles.';$('session').className=loggedIn?'logged-in':'';controls();return;}
    if(id!==scanId)return;
    if(type==='KURUKIN_ACQUISITION_STATE'){setState(p);return;}if(type==='KURUKIN_ACQUISITION_ERROR'){const d=p.diagnostic;$('acquisition-status').textContent=`${p.code} · ${d.baseHost}${d.httpStatus?` · HTTP ${d.httpStatus}`:''} · ${d.errorCode}`;return;}if(type==='KURUKIN_EXPERIMENTAL_AUDIO_RESULT'){$('experimental-result').textContent=`Experimental: ${p.audioClassification||'sin clasificación'} · Silero ${p.sileroMs} ms · YAMNet ${p.yamnetMs} ms`;return;}
    if(type==='KURUKIN_SCAN_PROGRESS'){const labels={preparing:'Preparando contexto…',requesting:'Consultando TikTok…',waiting:'Esperando…',received:'Página recibida'};$('status').textContent=labels[p.phase];$('bar').value=p.total;$('total').textContent=`${p.total} / ${$('bar').max} vídeos`;$('page').textContent=p.page;$('http').textContent=p.debug.httpStatus??'—';$('debug').textContent=JSON.stringify(p.debug,null,2);return;}
    if(type==='KURUKIN_SCAN_COMPLETE'){running=false;videos=N.exportVideos(p.videos).filter(v=>v.author.toLowerCase()===username?.toLowerCase());$('bar').value=videos.length;$('total').textContent=`${videos.length} / ${$('bar').max} vídeos`;$('status').textContent=p.cancelled?'Análisis cancelado':'Análisis completado';$('acquisition').hidden=p.cancelled||!videos.length;controls();return;}
    if(type==='KURUKIN_SCAN_ERROR'){running=false;$('status').textContent=p.code;controls();}
  });
  setInterval(()=>{if(running)$('elapsed').textContent=`${Math.floor((Date.now()-startedAt)/1000)} s`;},500);send('PANEL_READY',contextId);
})();
